### ISSUE TITLE
tornado project start failed

### ISSUE THREAD

**Issue by jizhouli** [Ethan-Zhang/mownfish#2]
Hi, Ethan
    I use mownfish to create a tornado project, when i exec following cmd

> python sugest/cmd/mownfishd.py --port=8086

   there an error happened as below

> Traceback (most recent call last):
  File "sugest/cmd/mownfishd.py", line 35, in <module>
    main()
  File "sugest/cmd/mownfishd.py", line 32, in main
    server.start()
  File "/home/guokr/platform/test/sugest/sugest/http_server.py", line 91, in start
    and value.value() is None:
AttributeError: 'str' object has no attribute 'value'

I don`t know if i use fishing cmd correctly or something else, eagerly awaiting your reply

**Comment by Ethan-Zhang** [comment]
Thank you for your testing, please checkout the latest version that I have fixed this problem.

**Comment by jizhouli** [comment]
It works! thx!!
